In [2]:
import pandas as pd 
file_path = "Data/online_retail_II.xlsx"
df_2009 = pd.read_excel(file_path, sheet_name = "Year 2009-2010")
df_2010 = pd.read_excel(file_path, sheet_name = "Year 2010-2011")

print("2009-2010:", df_2009.shape)
print("2010-2011:", df_2010.shape)

2009-2010: (525461, 8)
2010-2011: (541910, 8)

In [3]:
df_2009.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [4]:
df_2009.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.1+ MB

In [5]:
df_2009.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [6]:
df_2009.shape

(525461, 8)

In [7]:
df_2009.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [8]:
df_2009.duplicated().sum()

np.int64(6865)

In [10]:
df_2009.describe()

            Quantity                 InvoiceDate          Price    Customer ID
count  525461.000000                      525461  525461.000000  417534.000000
mean       10.337667  2010-06-28 11:37:36.845018       4.688834   15360.645478
min     -9600.000000         2009-12-01 07:45:00  -53594.360000   12346.000000
25%         1.000000         2010-03-21 12:20:00       1.250000   13983.000000
50%         3.000000         2010-07-06 09:51:00       2.100000   15311.000000
75%        10.000000         2010-10-15 12:45:00       4.210000   16799.000000
max     19152.000000         2010-12-09 20:01:00   25111.090000   18287.000000
std       107.424110                         NaN     146.126914    1680.811316